name: Generate README

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If there are any dependencies, install them here

    - name: Generate README
      run: |
        python readme_gen.py

    - name: Commit and push if it changed
      run: |
        git diff
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"
        git commit -am "Automated README update" || exit 0
        git push